### ISSUE TITLE
[BETA] TypeError: "_merge_bands() takes 0 positional arguments but 1 was given" with black and white screen

### ISSUE THREAD

**Issue by emilyboda** [aceisace/Inky-Calendar#123]
The screen I'm testing the beta with is a black and white screen so I've been running into some issues relating to that.

### Error when settings.json has "model": "epd_7_in_5"
```
pi@raspberrypi:~ $ python3
Python 3.7.3 (default, Dec 20 2019, 18:57:59)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from inkycal import Inkycal
>>> ink = Inkycal('/home/pi/Inkycal/settings.json', render = True)
Settings file OK!
Agenda loaded
loaded inkycal
>>> ink.test()
You are running inkycal v2.0.0beta
Running inkyal test-run for epd_7_in_5 ePaper
generating image for Agenda module...OK!
>>> ink.run()
Generating images for all modules...
OK
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/Inkycal/inkycal/main.py", line 189, in run
    im_black = self._merge_bands()
TypeError: _merge_bands() takes 0 positional arguments but 1 was given
>>> exit()
```

### No error when settings.json is changed to "model": "epd_7_in_5_colour"
```
pi@raspberrypi:~ $ python3
Python 3.7.3 (default, Dec 20 2019, 18:57:59)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from inkycal import Inkycal
>>> ink = Inkycal('/home/pi/Inkycal/settings.json', render = True)
Settings file OK!
Agenda loaded
loaded inkycal
>>> ink.test()
You are running inkycal v2.0.0beta
Running inkyal test-run for epd_7_in_5_colour ePaper
generating image for Agenda module...OK!
>>> ink.run()
Generating images for all modules...
OK
Initialising..Updating display......Done
Sending E-Paper to deep sleep...Done

inkycal has been running without any errors for 1 display updates
That was 29 seconds ago
13 Minutes left until next refresh
```
I'm no python master, but it doesn't look to me like line 189 in main.py is given any positional arguments, so I don't really know what it's talking about.
![confusion](https://user-images.githubusercontent.com/9170143/83925472-3f0b8600-a755-11ea-9a86-a216eeb15f3d.PNG)

**Comment by aceisace** [comment]
OK, pushed the fix for this issue in the BETA branch.
Closing this PR as this issue has been solved.
If you need to re-open this issue, please feel free to do so.
